apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-skills-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soft-skills-chatbot
  template:
    metadata:
      labels:
        app: soft-skills-chatbot
    spec:
      securityContext:
        runAsUser: 0            # Run all containers as this user (root in this case)
        runAsGroup: 0           # Run all containers in this group
        fsGroup: 0              # File system group for the pod
        seccompProfile:
          type: RuntimeDefault   # Security profile
      containers:                # Here is the corrected containers section
      - name: soft-skills-bot
        image: softskillsregistry.azurecr.io/softskillsbot:__IMAGE_TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: SLACK_BOT_TOKEN
        - name: COSMOS_DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: COSMOS_DB_CONNECTION_STRING
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_OPENAI_API_KEY
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_OPENAI_ENDPOINT
        - name: AZURE_REGION
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_REGION
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: AZURE_STORAGE_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_STORAGE_CONTAINER_NAME
        - name: AZURE_SPEECH_API_KEY
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_SPEECH_API_KEY
