apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-skills-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soft-skills-chatbot
  template:
    metadata:
      labels:
        app: soft-skills-chatbot
    spec:
      containers:
      - name: soft-skills-chatbot
        image: softskillsregistry.azurecr.io/softskillsbot:latest
        ports:
        - containerPort: 80
        env:
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: SLACK_BOT_TOKEN
        - name: COSMOS_DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: COSMOS_DB_CONNECTION_STRING
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_OPENAI_API_KEY
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_OPENAI_ENDPOINT
        - name: AZURE_REGION
          valueFrom:
            secretKeyRef:
              name: softskills-secrets
              key: AZURE_REGION
        # Include any other necessary environment variables
