name: CI/CD Pipeline for AKS

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: soft-skills-coach-rg
  AKS_CLUSTER: chatbot_cluster
  ACR_NAME: softskillsregistry

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      # Build and Push Docker Image with no-cache to avoid using old layers
      - name: Build and Push Docker Image
        run: |
          docker buildx build --no-cache --platform linux/arm64 -t ${{ env.ACR_NAME }}.azurecr.io/softskillsbot:${{ github.sha }} --push .

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}

      # Delete previous deployment (optional)
      - name: Delete previous Kubernetes deployment
        run: |
          kubectl delete deployment soft-skills-chatbot || true

      # Replace image tag dynamically in deployment.yaml
      - name: Update deployment.yaml with image tag
        run: |
          sed -i 's#__IMAGE_TAG__#${{ github.sha }}#g' deployment.yaml

      # Apply Kubernetes Deployment
      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yaml

      # Check Deployment Rollout Status
      - name: Check Deployment Status
        run: |
          kubectl rollout status deployment/soft-skills-chatbot
