name: CI/CD Pipeline for ARM Architecture on AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure using the service principal stored in GitHub Secrets
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: |
          az acr login --name softskillsregistry

      # Build and push the Docker image for ARM architecture
      - name: Build and Push Docker Image (ARM)
        run: |
          docker buildx build --platform linux/arm64 -t softskillsregistry.azurecr.io/chatbot-softskills:${{ github.sha }} --push .

      # Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group soft-skills-coach-rg --name chatbot_cluster

      # Update Kubernetes deployment with the new ARM image
      - name: Deploy to AKS
        run: |
          kubectl set image deployment/chatbot-deployment chatbot-container=softskillsregistry.azurecr.io/chatbot-softskills:${{ github.sha }}
